spring:
  config:
    activate:
      on-profile: default
  destination:
    name:
      s4Outbound: "API_OUTBOUND_DELIVERY"

  client:
    id: ${CLIENT.ID}
    secret: ${CLIENT.SECRET}
  service:
    url: wss://enterprise-messaging-messaging-gateway.cfapps.eu10.hana.ondemand.com/protocols/amqp10ws
  token:
    url: https://sapit-dataandintegration-dev.authentication.eu10.hana.ondemand.com/oauth/token

  datasource:
    url: "jdbc:sqlite:/Users/adubok/IdeaProjects/cap-eventmesh-demo/db.sqlite"
    #url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always

logging:
  level:
    ROOT: INFO