spring:
  config:
    activate:
      on-profile: cloud
  destination:
    name:
      s4Outbound: "OUTBOUND_DELIVERY_SRV"

#cds:
#  remote.services:
#    - name: OutboundDeliveryService
#  messaging.services:
#    hanesbrand-em:
#      kind: enterprise-messaging
#      subscribePrefix: '*'
#      queue:
#        name: "s4"

#  datasource:
#    url: "jdbc:sqlite:/Users/adubok/IdeaProjects/cap-eventmesh-demo/db.sqlite"
#    #url: "jdbc:sqlite:file::memory:?cache=shared"
#    driver-class-name: org.sqlite.JDBC
#    hikari:
#      maximum-pool-size: 1
#  sql:
#    init:
#      mode: always

logging:
  level:
    ROOT: INFO
